using TransparentAiAgentCore.Domain.Enums;

namespace TransparentAiAgentCore.Domain.Models;

/// <summary>
/// Messages generated by the application itself.
/// Represents system-driven actions, scenarios, automation, workflows, notifications.
/// NOTE: "Application" is used instead of "System" to avoid confusion with LLM system prompts.
/// RULE: Use when system translated user action into message, or application logic generated content.
/// </summary>
public abstract class ApplicationMessage : IMessage
{
    public Guid Id { get; protected set; }
    public abstract MessageRole Role { get; } // Can be User, Assistant, or other
    public string Content { get; protected set; } = string.Empty;
    public DateTime Timestamp { get; protected set; }
    public MessageContextStatus ContextStatus { get; set; }
    public abstract string MessageTypeDiscriminator { get; }

    /// <summary>
    /// Type of application message for identification and routing.
    /// Examples: "scenario_user_message", "tool_update", "context_injection"
    /// </summary>
    public string MessageType { get; protected set; } = string.Empty;
}
