<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.AI.OpenAI" Version="2.5.0-beta.1" />
    <PackageReference Include="Azure.Identity" Version="1.13.1" />
    <PackageReference Include="OpenAI" Version="2.7.0" />
    <PackageReference Include="ModelContextProtocol" Version="0.4.0-preview.3" />
    <PackageReference Include="System.Text.Json" Version="9.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Anthropic.Client">
      <HintPath>..\lib\Anthropic.Client\Anthropic.Client.dll</HintPath>
      <Private>True</Private>
    </Reference>
  </ItemGroup>

</Project>
